### ISSUE TITLE
Why only long press?

### ISSUE THREAD

**Issue by Tristannos** [rasitayaz/flutter-pie-menu#18]
Please implement a option to only press,
would be much easier.

Thank you!!!!

**Comment by rasitayaz** [comment]
Thanks for your feedback, that's a good idea. You can set `delayDuration` feature of the `PieTheme` to `Duration.zero` as a workaround for now. 👍

**Comment by Tristannos** [comment]
alright thankyou

**Comment by rasitayaz** [comment]
> @rasitayaz And if you click it again to dismiss?

You can dismiss by clicking outside of the center circle and the buttons, but it would be a nice feature to be able to dismiss by clicking at the center again, noted. 👍

**Comment by rasitayaz** [comment]
@Tristannos you can now dismiss the menu by clicking it again with the version 1.1.0.
