### ISSUE TITLE
disappear in list view

### ISSUE THREAD

**Issue by soulonej** [rasitayaz/flutter-pie-menu#23]
I have tried the example, in ListView the item will be disappear if it is long press,

**Comment by rasitayaz** [comment]
did you try the android demo? can you share a video?

**Comment by soulonej** [comment]
Flutter (Channel stable, 3.0.5, on macOS 12.6 21G115 darwin-x64, locale en-HK)
    • Flutter version 3.0.5 at /Users/soulone/documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (9 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2
    
    IOS 16.0, Simulator 14 Pro Max
https://user-images.githubusercontent.com/54014126/190680350-f741a534-d45d-4c31-83d8-e4b3b0cd1842.MOV

**Comment by rasitayaz** [comment]
i will try to investigate this but i haven't tested the package on an ios device or emulator before.

have you tried it on any other platform like android or macos? do they also have the same issue?

**Comment by soulonej** [comment]
it works under  Android 11 (API 30) (emulator)

**Comment by rasitayaz** [comment]
thanks for your efforts, i'll try to fix this as soon as possible.

**Comment by rasitayaz** [comment]
apparently the issue is related to `didChangeMetrics()` is being called unnecessarily on ios devices, found a [similar issue here](https://github.com/flutter/flutter/issues/89824) but it seems the team could not reproduce the issue. i've added an extra check to see if the screen size changed or not, which fixed the issue.
