### ISSUE TITLE
How to disable child fade out when pressing menu widget

### ISSUE THREAD

**Issue by xetra11** [rasitayaz/flutter-pie-menu#25]
I have the `PieCanvas` wrapping a whole page and at the `PieMenu` section for the child I wrap the actual menu button. However as soon as the button is pressed the whole wrapped menu disappears and only the radial PieActions become visible. How can I disable the disappearance of the wrapped elements or is there a way to make the PieActions float over the underlying elements?

**Comment by rasitayaz** [comment]
i'm not sure i understand the issue, can you share a screenshot of the page with menu both visible and hidden for demonstration?
