### ISSUE TITLE
Is it possible to not use pointer offset?

### ISSUE THREAD

**Issue by sadespresso** [rasitayaz/flutter-pie-menu#50]
Currently, the actions will be placed around the touch point (offset):

![image](https://github.com/rasitayaz/flutter-pie-menu/assets/51638223/ec542e7f-2bbb-444e-85ab-6f6ad8b71887)
![image](https://github.com/rasitayaz/flutter-pie-menu/assets/51638223/078036eb-4741-4679-b6e7-c3ba8930618c)

Is it possible to place the actions around the center of the `child` regardless of the pointer offset?
![image](https://github.com/rasitayaz/flutter-pie-menu/assets/51638223/926bfacf-2bb2-450b-9c74-de6940c74ae6)

**Comment by rasitayaz** [comment]
not right now but good idea! I'll work on this when I get the chance.

**Comment by sadespresso** [comment]
I have done a quick implementation, please take a look at this if you have a time.

https://github.com/sadespresso/flutter-pie-menu/commit/69c45eeab83458ef5e7e0ea0f23e90e34fd2b667

Not sure about what to test for now, but I'll make a PR and improve if you approve :)

Thank you, awesome package!!!

**Comment by rasitayaz** [comment]
sure, pull requests are welcome
