### ISSUE TITLE
PieMenu loose the context after select

### ISSUE THREAD

**Issue by Paroca72** [rasitayaz/flutter-pie-menu#58]
Hello,

I have a complex widget as child of PieMenu.
Inside this widget I need to recall the some properties from the ancestor like:
```    
final user = InheritedUser.of(context).user;
```

But after select the PieMenu the child it seems redraw with another context and cannot retrieve anymore the settings I needs.

Thanks for your help
Sam

**Comment by Paroca72** [comment]
I took a look to the code and I think the easiest solution is to provide another nullable child (childPressed) that is showed when the menu is out.
So the user can implement a more simple widget without context issues.

Thanks

**Comment by rasitayaz** [comment]
You need to set `overlayStyle` to [`PieOverlayStyle.around`](https://github.com/rasitayaz/flutter-pie-menu/blob/main/lib/src/pie_theme.dart#L19-L24) in your pie theme if you want to preserve the state of your menu child.
